#ifndef DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_PLUGIN_INFO_H_INCLUDED

#define DISTRHO_PLUGIN_BRAND   "Grog"
#define DISTRHO_PLUGIN_NAME    "Grog Synth"
#define DISTRHO_PLUGIN_URI     "https://github.com/HITOA/grog"
#define DISTRHO_PLUGIN_CLAP_ID "Grog.GrogSynth"

#define DISTRHO_PLUGIN_BRAND_ID  GrgB
#define DISTRHO_PLUGIN_UNIQUE_ID GrgS

#define DISTRHO_PLUGIN_HAS_UI           1
#define DISTRHO_PLUGIN_IS_RT_SAFE       1
#define DISTRHO_PLUGIN_NUM_INPUTS       2
#define DISTRHO_PLUGIN_NUM_OUTPUTS      2
#define DISTRHO_PLUGIN_WANT_PROGRAMS    0
#define DISTRHO_UI_FILE_BROWSER         0
#define DISTRHO_UI_USER_RESIZABLE       1
#define DISTRHO_UI_DEFAULT_WIDTH        512
#define DISTRHO_UI_DEFAULT_HEIGHT       512
#define DISTRHO_PLUGIN_WANT_TIMEPOS     1
#define DISTRHO_PLUGIN_WANT_MIDI_INPUT  1

#endif // DISTRHO_PLUGIN_INFO_H_INCLUDED